services:
  dde:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - DDE_DATA_DIR=/app/.data/projects
    volumes:
      - ./.data:/app/.data
    stdin_open: true
    tty: true
